blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussion
    url: https://github.com/leekaize/ichido/discussions
    about: Questions, ideas, community chat
  - name: ðŸ“– Documentation
    url: https://github.com/leekaize/ichido#readme
    about: Read the docs first
